#!/usr/bin/env python3
"""Curriculum catalog: parse notebooks + the track manifest, derive the index.

Notebooks own their mechanical metadata (docstring, ``(Track, Rung)`` tag,
``app_title``, PEP 723 deps, headings, source-reading links). The authored
overlay — topic prose, mastery, status, architecture pointers, and the M:N
track↔notebook links — lives in ``notes/curriculum.toml``. This script merges
the two grains and renders ``notes/taxonomy.md`` (generated, never
hand-edited); ``check`` exits nonzero when a committed render is stale or the
sources disagree, which is what CI runs.

Stdlib-only on purpose (``tomllib`` + ``re`` + ``ast``): runs under
``uv run`` with zero added dependencies, same as ``check_licenses.py``,
whose PEP 723 helpers it reuses.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from check_licenses import _BLOCK_RE, dependency_name, pep723_dependencies

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "notes" / "curriculum.toml"
TAXONOMY = REPO_ROOT / "notes" / "taxonomy.md"
HEAD = REPO_ROOT / "notes" / "taxonomy.head.md"
FOOT = REPO_ROOT / "notes" / "taxonomy.foot.md"
CI_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "ci.yml"

BANNER = (
    "<!-- generated by scripts/curriculum.py render — edit notes/curriculum.toml"
    " and the notebooks, not this file -->"
)

#: Docstring tag, anchored to the end of the summary line: ``(B1, L2)``.
_TAG_RE = re.compile(r"\((?P<track>[A-Za-z0-9]+), (?P<rung>L[1-4])\)\.?\s*$")
_APP_TITLE_RE = re.compile(r'app_title="(?P<title>[^"]+)"')
_UPSTREAM_RE = re.compile(r"Upstream: <(?P<url>https://[^>]+)>")
_CLONE_RE = re.compile(r"Local clone [^:]*: `(?P<path>[^`]+)`")
_HEADING_RE = re.compile(r"^\s*#{1,6} +(?P<text>\S.*)$", re.MULTILINE)


@dataclass
class Notebook:
    """Grain A — one record per notebook file, all fields parsed from it."""

    path: str
    domain: str
    library: str
    seq: int
    title: str
    summary: str
    track: str | None
    rung: str | None
    packages: list[str]
    requires_python: str | None
    headings: list[str]
    has_tests: bool
    upstream_url: str | None
    clone_path: str | None


@dataclass
class Track:
    """Grain B — one record per taxonomy row, authored in curriculum.toml."""

    id: str
    domain: str
    topic: str
    mastery: str
    status: str
    notebooks: list[dict[str, str]]
    note: str | None = None
    sibling_curricula: list[str] = field(default_factory=list)
    architecture: list[str] = field(default_factory=list)
    architecture_missing: list[str] = field(default_factory=list)
    packages: str = ""
    license_status: str = ""


def _string_literals(tree: ast.Module) -> list[str]:
    """Collect every string constant in the module — mo.md bodies, docstrings."""
    return [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
    ]


def _requires_python(source: str) -> str | None:
    """Return the PEP 723 block's ``requires-python`` field, if present."""
    match = _BLOCK_RE.search(source)
    if match is None:
        return None
    import tomllib

    toml_text = "\n".join(
        line.removeprefix("# ").removeprefix("#") for line in match.group(1).splitlines()
    )
    value = tomllib.loads(toml_text).get("requires-python")
    return str(value) if value is not None else None


def parse_notebook(path: Path) -> Notebook:
    """Parse one notebook file into its Grain-A record."""
    rel = path.relative_to(REPO_ROOT).as_posix()
    _, domain, library, filename = rel.split("/", 3)
    seq = int(filename.split("_", 1)[0])
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    docstring = ast.get_docstring(tree) or ""
    summary_line = docstring.splitlines()[0] if docstring else ""

    tag = _TAG_RE.search(summary_line)
    track = tag.group("track") if tag else None
    rung = tag.group("rung") if tag else None
    summary = _TAG_RE.sub("", summary_line).rstrip()
    if summary and not summary.endswith("."):
        summary += "."

    title_match = _APP_TITLE_RE.search(source)
    title = title_match.group("title") if title_match else summary

    literals = _string_literals(tree)
    headings = [
        m.group("text").strip()
        for text in literals
        if "\n" in text
        for m in _HEADING_RE.finditer(text)
    ]
    upstream = next((m.group("url") for s in literals for m in [_UPSTREAM_RE.search(s)] if m), None)
    clone = next((m.group("path") for s in literals for m in [_CLONE_RE.search(s)] if m), None)

    return Notebook(
        path=rel,
        domain=domain,
        library=library,
        seq=seq,
        title=title,
        summary=summary,
        track=track,
        rung=rung,
        packages=sorted({dependency_name(r) for r in pep723_dependencies(path)}),
        requires_python=_requires_python(source),
        headings=headings,
        has_tests=bool(re.search(r"^def test_", source, re.MULTILINE)),
        upstream_url=upstream,
        clone_path=clone,
    )


def load_tracks() -> list[Track]:
    """Load the authored track overlay from notes/curriculum.toml."""
    import tomllib

    with MANIFEST.open("rb") as f:
        data = tomllib.load(f)
    return [Track(**raw) for raw in data["track"]]


def load_ladder() -> dict[str, str]:
    """Return the short rung labels (L1..L4) used to caption rollups."""
    import tomllib

    with MANIFEST.open("rb") as f:
        return dict(tomllib.load(f)["ladder"])


def notebook_paths() -> list[Path]:
    """Every notebook on disk, sorted (the template is not a notebook)."""
    return sorted(REPO_ROOT.glob("notebooks/**/*.py"))


def index() -> tuple[list[Notebook], list[Track]]:
    """Return the merged model: parsed notebooks + the authored track overlay."""
    return [parse_notebook(p) for p in notebook_paths()], load_tracks()


def _notebook_cell(track: Track) -> str:
    """Render one row's Notebook column: links · ✎ siblings (note)."""
    items = [
        f"[{nb.get('label', nb['path'])}](../{nb['path']})" for nb in track.notebooks
    ]
    items.extend(track.sibling_curricula)
    cell = " · ".join(items) if items else "—"
    if track.note:
        cell += f" ({track.note})"
    return cell


def _architecture_cell(track: Track) -> str:
    """Render one row's Architecture column: `architecture/{...}` (missing: ...)."""
    parts: list[str] = []
    if track.architecture:
        parts.append("`architecture/{" + ",".join(track.architecture) + "}`")
    if track.architecture_missing:
        parts.append("(missing: " + ", ".join(track.architecture_missing) + ")")
    return " ".join(parts) if parts else "—"


def render_taxonomy() -> str:
    """Render the full generated notes/taxonomy.md content."""
    tracks = load_tracks()
    rows = [
        "| Domain | Track | Topic | Notebook | Architecture study | Packages "
        "| License status | Mastery | Status |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    rows.extend(
        f"| {t.domain} | {t.id} | {t.topic} | {_notebook_cell(t)} "
        f"| {_architecture_cell(t)} | {t.packages} | {t.license_status} "
        f"| {t.mastery} | {t.status} |"
        for t in tracks
    )
    head = HEAD.read_text(encoding="utf-8").strip("\n")
    foot = FOOT.read_text(encoding="utf-8").strip("\n")
    return "\n".join([BANNER, "", head, "", *rows, "", foot, ""])


def render(write: bool = True) -> dict[Path, str]:
    """Render every generated artifact; write them unless dry-running."""
    artifacts = {TAXONOMY: render_taxonomy()}
    if write:
        for path, content in artifacts.items():
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    return artifacts


def check_drift() -> int:
    """Drift gate: nonzero when sources disagree or a render is stale."""
    notebooks, tracks = index()
    errors: list[str] = []
    warnings: list[str] = []

    claimed: dict[str, list[str]] = {}
    for track in tracks:
        for nb in track.notebooks:
            claimed.setdefault(nb["path"], []).append(track.id)
            if not (REPO_ROOT / nb["path"]).exists():
                errors.append(f"{track.id}: claims missing file {nb['path']}")

    # Rename-hazard parity: a `git mv` or an unclaimed new notebook fails here.
    for nb in notebooks:
        owners = claimed.get(nb.path, [])
        if not owners:
            errors.append(f"unclaimed notebook (no [[track]] lists it): {nb.path}")
        elif nb.track is not None and nb.track not in owners:
            warnings.append(
                f"{nb.path}: docstring tag ({nb.track}) is not a claiming track "
                f"({', '.join(owners)})"
            )
        if nb.track is None:
            warnings.append(f"{nb.path}: no (Track, Rung) docstring tag")

    ci_text = CI_WORKFLOW.read_text(encoding="utf-8")
    warnings.extend(
        f"{nb.path}: not in the ci.yml smoke step (hand-maintained — add it "
        "or note why not)"
        for nb in notebooks
        if nb.path not in ci_text
    )

    for path, content in render(write=False).items():
        rel = path.relative_to(REPO_ROOT)
        if not path.exists():
            errors.append(f"{rel}: missing — run `uv run scripts/curriculum.py render`")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"{rel}: stale — run `uv run scripts/curriculum.py render`")

    for warning in warnings:
        print(f"WARN  {warning}")
    for error in errors:
        print(f"DRIFT {error}")
    if errors:
        print(f"Curriculum drift: {len(errors)} error(s), {len(warnings)} warning(s).")
        return 1
    print(
        f"Curriculum drift: OK ({len(notebooks)} notebooks, {len(tracks)} tracks, "
        f"{len(warnings)} warning(s))"
    )
    return 0


def main() -> int:
    """CLI: render (write generated files) or check (the CI drift gate)."""
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("render", help="regenerate notes/taxonomy.md from the sources")
    sub.add_parser("check", help="exit nonzero on drift between sources and renders")
    args = parser.parse_args()
    if args.command == "render":
        render()
        return 0
    return check_drift()


if __name__ == "__main__":
    sys.exit(main())
