#!/usr/bin/env python3
"""Curriculum catalog: parse notebooks + the track manifest, derive the index.

Notebooks own their mechanical metadata (docstring, ``app_title``, PEP 723
deps, headings, source-reading links). The authored overlay — topic prose,
mastery, status, per-notebook rung, the project registry, and the M:N
track↔notebook links — lives in ``notes/curriculum.toml``. This script merges
the two grains and renders ``notes/taxonomy.md`` (generated, never
hand-edited); ``check`` exits nonzero when a committed render is stale or the
sources disagree, which is what CI runs.

Stdlib-only on purpose (``tomllib`` + ``re`` + ``ast``): runs under
``uv run`` with zero added dependencies, same as ``check_licenses.py``,
whose PEP 723 helpers it reuses.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path

from check_licenses import _BLOCK_RE, dependency_name, pep723_dependencies

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "notes" / "curriculum.toml"
TAXONOMY = REPO_ROOT / "notes" / "taxonomy.md"
HEAD = REPO_ROOT / "notes" / "taxonomy.head.md"
FOOT = REPO_ROOT / "notes" / "taxonomy.foot.md"
CATALOG = REPO_ROOT / "notes" / "catalog.jsonl"
COVERAGE = REPO_ROOT / "notes" / "coverage.md"
SOURCES = REPO_ROOT / "notes" / "sources.jsonl"
CI_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "ci.yml"

#: The architecture-study corpus — a RESEARCH input, never a runtime dependency.
#: `sources.jsonl` is built from it locally and committed as portable URLs; when
#: the corpus is absent (CI, or a fresh clone) the builder skips and the
#: committed file is used as-is.
ARCH_ROOT = Path(
    os.environ.get("ARCH_ROOT", str(Path.home() / "work" / "notes" / "notes" / "architecture"))
).expanduser()
#: Which LLM-variant study to read, in order of preference.
_LLM_PREFERENCE = ("claude", "Codex", "codex", "grok")
_MD_LINK_RE = re.compile(r"\[(?P<title>[^\]]+)\]\((?P<url>https://github\.com/[^)\s>]+)\)")
#: A version-pinned source link: github.com/<owner>/<repo>/blob/<ref>/<path>. The
#: pinned ref is the authoritative baseline — studies phrase their prose "Source:"
#: line inconsistently (`@ \`sha\``, `/tree/<tag>`), but the blob URLs never lie.
_BLOB_RE = re.compile(r"(?P<base>https://github\.com/[^/\s]+/[^/\s]+)/blob/(?P<tag>[^/\s]+)/")
#: Keep the map at component grain — a handful of files per component, and a
#: project ceiling so a big library can't dominate the committed artifact.
_PER_COMPONENT = 8
_PER_PROJECT = 60

BANNER = (
    "<!-- generated by scripts/curriculum.py render — edit notes/curriculum.toml"
    " and the notebooks, not this file -->"
)

_APP_TITLE_RE = re.compile(r'app_title="(?P<title>[^"]+)"')
_UPSTREAM_RE = re.compile(r"Upstream: <(?P<url>https://[^>]+)>")
_HEADING_RE = re.compile(r"^\s*#{1,6} +(?P<text>\S.*)$", re.MULTILINE)
#: A track id is a readable ``domain/slug``: lowercase, hyphen-separated.
_SLUG_RE = re.compile(r"^[a-z][a-z0-9-]*/[a-z0-9-]+$")
#: Cross-reference lines authored in a notebook's source-reading cell, parsed the
#: same way ``Upstream:`` is — ``- Concepts: a, b, c`` and ``- See also:
#: `notebooks/…\.py` — note``. Concepts join to the registry; see-also to notebooks.
_CONCEPTS_RE = re.compile(r"^\s*[-*]\s*Concepts:\s*(?P<body>.+)$", re.MULTILINE)
_SEE_ALSO_RE = re.compile(r"^\s*[-*]\s*See also:\s*(?P<body>.+)$", re.MULTILINE)
_SEE_ALSO_PATH_RE = re.compile(r"`(?P<path>notebooks/[\w./-]+\.py)`")


@dataclass
class Notebook:
    """Grain A — one record per notebook file, all fields parsed from it."""

    path: str
    domain: str
    library: str
    seq: int
    title: str
    summary: str
    track: str | None
    rung: str | None
    packages: list[str]
    requires_python: str | None
    headings: list[str]
    has_tests: bool
    upstream_url: str | None
    #: Cross-references authored in the source-reading cell (both opt-in): the
    #: concept slugs this notebook teaches, and the notebooks it points readers to.
    concepts: list[str] = field(default_factory=list)
    see_also: list[str] = field(default_factory=list)


@dataclass
class Concept:
    """A teaching concept — the dimension that joins notebooks, sources, projects.

    Authored in curriculum.toml; the gloss is our own one-line prose.
    """

    id: str
    gloss: str
    projects: list[str] = field(default_factory=list)
    #: An optional canonical implementation — a portable pinned URL from sources.jsonl.
    source: str | None = None


@dataclass
class Track:
    """Grain B — one course per taxonomy row, authored in curriculum.toml.

    ``id`` is a readable ``domain/slug`` (e.g. ``data/dataframes``); the domain
    is derived from it, never authored separately.
    """

    id: str
    topic: str
    mastery: str
    status: str
    notebooks: list[dict[str, str]]
    note: str | None = None
    sibling_curricula: list[str] = field(default_factory=list)
    architecture: list[str] = field(default_factory=list)
    architecture_missing: list[str] = field(default_factory=list)
    packages: str = ""
    license_status: str = ""

    @property
    def domain(self) -> str:
        """The named domain, the slug's first segment (data/dataframes -> data)."""
        return self.id.split("/", 1)[0]


@dataclass
class Project:
    """Grain C — one studied library, the join spine across the corpora.

    ``name`` matches the notebook library directory, so a notebook resolves to
    its project by path (``notebooks/data/polars/…`` → project ``polars``).
    """

    name: str
    tracks: list[str]
    upstream: str | None = None
    rust_in_python: str | None = None
    #: The architecture-study directory under the corpus, when it differs from
    #: ``name`` (e.g. ``pyarrow`` -> ``arrow``). Omitted when it matches name or
    #: the project has no study; the source-map builder falls back to ``name``.
    architecture: str | None = None
    #: Lineage edge — the project(s) this one is built on (``polars`` -> ``arrow``).
    derives_from: list[str] = field(default_factory=list)


def _string_literals(tree: ast.Module) -> list[str]:
    """Collect every string constant in the module — mo.md bodies, docstrings."""
    return [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
    ]


def _requires_python(source: str) -> str | None:
    """Return the PEP 723 block's ``requires-python`` field, if present."""
    match = _BLOCK_RE.search(source)
    if match is None:
        return None
    import tomllib

    toml_text = "\n".join(
        line.removeprefix("# ").removeprefix("#") for line in match.group(1).splitlines()
    )
    value = tomllib.loads(toml_text).get("requires-python")
    return str(value) if value is not None else None


def parse_notebook(path: Path) -> Notebook:
    """Parse one notebook file into its Grain-A record."""
    rel = path.relative_to(REPO_ROOT).as_posix()
    _, domain, library, filename = rel.split("/", 3)
    seq = int(filename.split("_", 1)[0])
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    docstring = ast.get_docstring(tree) or ""
    summary = docstring.splitlines()[0].rstrip() if docstring else ""
    if summary and not summary.endswith("."):
        summary += "."

    title_match = _APP_TITLE_RE.search(source)
    title = title_match.group("title") if title_match else summary

    literals = _string_literals(tree)
    headings = [
        m.group("text").strip()
        for text in literals
        if "\n" in text
        for m in _HEADING_RE.finditer(text)
    ]
    upstream = next((m.group("url") for s in literals for m in [_UPSTREAM_RE.search(s)] if m), None)
    concepts, see_also = _parse_cross_refs(literals)

    return Notebook(
        path=rel,
        domain=domain,
        library=library,
        seq=seq,
        title=title,
        summary=summary,
        track=None,
        rung=None,
        packages=sorted({dependency_name(r) for r in pep723_dependencies(path)}),
        requires_python=_requires_python(source),
        headings=headings,
        has_tests=bool(re.search(r"^def test_", source, re.MULTILINE)),
        upstream_url=upstream,
        concepts=concepts,
        see_also=see_also,
    )


def _parse_cross_refs(literals: list[str]) -> tuple[list[str], list[str]]:
    """Extract ``Concepts:`` slugs and ``See also:`` notebook paths from prose.

    Both are opt-in: a notebook with neither line parses to empty lists. Order is
    preserved and duplicates dropped, so the catalog record is deterministic.
    """
    concepts: list[str] = []
    see_also: list[str] = []
    for text in literals:
        for match in _CONCEPTS_RE.finditer(text):
            concepts.extend(
                slug for raw in match.group("body").split(",") if (slug := raw.strip().strip("`"))
            )
        for match in _SEE_ALSO_RE.finditer(text):
            body = match.group("body")
            see_also.extend(m.group("path") for m in _SEE_ALSO_PATH_RE.finditer(body))
    return list(dict.fromkeys(concepts)), list(dict.fromkeys(see_also))


def load_tracks() -> list[Track]:
    """Load the authored track overlay from notes/curriculum.toml."""
    import tomllib

    with MANIFEST.open("rb") as f:
        data = tomllib.load(f)
    return [Track(**raw) for raw in data["track"]]


def load_ladder() -> dict[str, str]:
    """Return the worded rung ladder (fundamentals..production) and descriptions."""
    import tomllib

    with MANIFEST.open("rb") as f:
        return dict(tomllib.load(f)["ladder"])


def load_projects() -> list[Project]:
    """Load the authored project registry from notes/curriculum.toml."""
    import tomllib

    with MANIFEST.open("rb") as f:
        data = tomllib.load(f)
    return [Project(**raw) for raw in data.get("project", [])]


def load_concepts() -> list[Concept]:
    """Load the authored concept registry from notes/curriculum.toml."""
    import tomllib

    with MANIFEST.open("rb") as f:
        data = tomllib.load(f)
    return [Concept(**raw) for raw in data.get("concept", [])]


def load_sources() -> list[dict[str, str]]:
    """Read the committed portable source map — no corpus needed, [] if absent."""
    if not SOURCES.exists():
        return []
    return [
        json.loads(line)
        for line in SOURCES.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def notebook_rungs(tracks: list[Track]) -> dict[str, str]:
    """Map each notebook path to its authored per-notebook rung (word)."""
    rungs: dict[str, str] = {}
    for track in tracks:
        for nb in track.notebooks:
            if "rung" in nb:
                rungs[nb["path"]] = nb["rung"]
    return rungs


def _study_dir(project: Project) -> Path | None:
    """Return the project's preferred study-variant dir, or None if absent."""
    base = ARCH_ROOT / (project.architecture or project.name)
    if not base.is_dir():
        return None
    variants = {d.name: d for d in base.iterdir() if d.is_dir()}
    for pref in _LLM_PREFERENCE:
        if pref in variants:
            return variants[pref]
    return next(iter(v for _, v in sorted(variants.items())), None)


def _project_sources(project: Project) -> list[dict[str, str]]:
    """Parse one project's study into portable (component -> source URL) records.

    Reads the corpus; returns [] when the project has no study on disk.
    """
    study = _study_dir(project)
    if study is None:
        return []
    sub = study / "subcomponents"
    root_toc = sub / "00-table-of-contents.md"
    if not root_toc.is_file():
        return []
    records: list[dict[str, str]] = []
    comp_root = sub / "components"
    comp_dirs = sorted(d for d in comp_root.iterdir() if d.is_dir()) if comp_root.is_dir() else []
    project_seen: set[str] = set()  # dedupe across components and bound the project
    for comp_dir in comp_dirs:
        if len(project_seen) >= _PER_PROJECT:
            break
        # Source links live in the component TOC for some studies, only in the
        # leaf docs for others — scan both, dedupe by URL, cap to a handful so
        # this stays component-grain, not a full file-by-file index.
        comp_count = 0
        for md in sorted(comp_dir.glob("**/*.md")):
            if comp_count >= _PER_COMPONENT or len(project_seen) >= _PER_PROJECT:
                break
            for link in _MD_LINK_RE.finditer(md.read_text(encoding="utf-8")):
                url = link.group("url")
                blob = _BLOB_RE.match(url)
                if blob is None or url in project_seen:  # pinned source files only, no dupes
                    continue
                project_seen.add(url)
                comp_count += 1
                records.append(
                    {
                        "project": project.name,
                        "baseline": f"{blob['base']}/tree/{blob['tag']}",
                        "tag": blob["tag"],
                        "component": comp_dir.name,
                        "title": link.group("title").strip(),
                        "url": url,
                    }
                )
                if comp_count >= _PER_COMPONENT or len(project_seen) >= _PER_PROJECT:
                    break
    return records


def render_sources() -> str | None:
    """Build the portable source map from the corpus; None when ARCH_ROOT absent."""
    if not ARCH_ROOT.exists():
        return None
    records = [rec for p in load_projects() for rec in _project_sources(p)]
    return "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in records)


def run_sources() -> int:
    """Rebuild notes/sources.jsonl from the corpus (a local-only research input)."""
    content = render_sources()
    if content is None:
        print(
            f"sources: corpus not found at {ARCH_ROOT} — skipped; the committed "
            "notes/sources.jsonl stands (it is portable, no corpus needed to use)."
        )
        return 0
    SOURCES.write_text(content, encoding="utf-8")
    print(f"wrote notes/sources.jsonl ({content.count(chr(10))} source links)")
    return 0


def source_map_errors(projects: list[Project]) -> list[str]:
    """Validate the committed sources.jsonl's shape — hermetic, no corpus needed."""
    if not SOURCES.exists():
        return []
    names = {p.name for p in projects}
    errors: list[str] = []
    for i, raw in enumerate(SOURCES.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            errors.append(f"sources.jsonl:{i}: invalid JSON")
            continue
        if rec.get("project") not in names:
            errors.append(f"sources.jsonl:{i}: unknown project {rec.get('project')!r}")
        url = rec.get("url", "")
        if not (url.startswith("https://github.com/") and "/blob/" in url):
            errors.append(f"sources.jsonl:{i}: not a pinned github blob URL: {url!r}")
        if "/home/" in line:
            errors.append(f"sources.jsonl:{i}: contains a local path")
    return errors


def notebook_paths() -> list[Path]:
    """Every notebook on disk, sorted (the template is not a notebook)."""
    return sorted(REPO_ROOT.glob("notebooks/**/*.py"))


def index() -> tuple[list[Notebook], list[Track]]:
    """Return the merged model: notebooks joined to the authored registry.

    A notebook's ``track`` and ``rung`` are not in the notebook anymore — they
    are sourced here from the registry: ``track`` is its primary claiming
    track's id, ``rung`` is the per-notebook rung authored on that claim.
    """
    notebooks = [parse_notebook(p) for p in notebook_paths()]
    tracks = load_tracks()
    claimed = claims(tracks)
    rungs = notebook_rungs(tracks)
    for nb in notebooks:
        primary = _primary_track(nb, claimed.get(nb.path, []))
        nb.track = primary.id if primary else None
        nb.rung = rungs.get(nb.path)
    return notebooks, tracks


def _notebook_cell(track: Track) -> str:
    """Render one row's Notebook column: links · ✎ siblings (note)."""
    items = [f"[{nb.get('label', nb['path'])}](../{nb['path']})" for nb in track.notebooks]
    items.extend(track.sibling_curricula)
    cell = " · ".join(items) if items else "—"
    if track.note:
        cell += f" ({track.note})"
    return cell


def _architecture_cell(track: Track) -> str:
    """Render one row's Architecture column: `architecture/{...}` (missing: ...)."""
    parts: list[str] = []
    if track.architecture:
        parts.append("`architecture/{" + ",".join(track.architecture) + "}`")
    if track.architecture_missing:
        parts.append("(missing: " + ", ".join(track.architecture_missing) + ")")
    return " ".join(parts) if parts else "—"


def render_taxonomy() -> str:
    """Render the full generated notes/taxonomy.md content."""
    tracks = load_tracks()
    rows = [
        "| Domain | Track | Topic | Notebook | Architecture study | Packages "
        "| License status | Mastery | Status |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    rows.extend(
        f"| {t.domain} | {t.id} | {t.topic} | {_notebook_cell(t)} "
        f"| {_architecture_cell(t)} | {t.packages} | {t.license_status} "
        f"| {t.mastery} | {t.status} |"
        for t in tracks
    )
    head = HEAD.read_text(encoding="utf-8").strip("\n")
    foot = FOOT.read_text(encoding="utf-8").strip("\n")
    return "\n".join([BANNER, "", head, "", *rows, "", foot, ""])


def claims(tracks: list[Track]) -> dict[str, list[Track]]:
    """Map each claimed notebook path to the tracks that list it."""
    claimed: dict[str, list[Track]] = {}
    for track in tracks:
        for nb in track.notebooks:
            claimed.setdefault(nb["path"], []).append(track)
    return claimed


def _primary_track(notebook: Notebook, owners: list[Track]) -> Track | None:
    """Pick the notebook's primary track: the lowest-id claiming track.

    Sorted for determinism — a notebook claimed by several tracks (e.g.
    pyarrow/001 under two) always resolves to the same primary.
    """
    if notebook.track is not None:
        for track in owners:
            if track.id == notebook.track:
                return track
    return min(owners, key=lambda t: t.id) if owners else None


def render_catalog() -> str:
    """Render notes/catalog.jsonl — one merged record per notebook, for jq/DuckDB."""
    notebooks, tracks = index()
    claimed = claims(tracks)
    lines = []
    for nb in notebooks:
        owners = claimed.get(nb.path, [])
        primary = _primary_track(nb, owners)
        record = {
            "path": nb.path,
            "domain": nb.domain,
            "library": nb.library,
            "seq": nb.seq,
            "title": nb.title,
            "summary": nb.summary,
            "track": nb.track,
            "rung": nb.rung,
            "tracks": [t.id for t in owners],
            "status": primary.status if primary else None,
            "mastery": primary.mastery if primary else None,
            "packages": nb.packages,
            "requires_python": nb.requires_python,
            "headings": nb.headings,
            "has_tests": nb.has_tests,
            "upstream_url": nb.upstream_url,
            "concepts": nb.concepts,
            "see_also": nb.see_also,
        }
        lines.append(json.dumps(record, ensure_ascii=False))
    return "\n".join(lines) + "\n"


def _count_table(header: tuple[str, str], counts: dict[str, int]) -> list[str]:
    """Render a two-column markdown count table."""
    rows = [f"| {header[0]} | {header[1]} |", "|---|---|"]
    rows.extend(f"| {key} | {count} |" for key, count in counts.items())
    return rows


def render_coverage() -> str:
    """Render notes/coverage.md — rollups and gap lists over the merged model."""
    notebooks, tracks = index()
    ladder = load_ladder()
    ci_text = CI_WORKFLOW.read_text(encoding="utf-8")

    rung_counts = {
        f"{rung} — {label}": sum(1 for nb in notebooks if nb.rung == rung)
        for rung, label in ladder.items()
    }
    rungless = sorted(nb.path for nb in notebooks if nb.rung is None)
    if rungless:
        rung_counts["no rung"] = len(rungless)

    status_counts: dict[str, int] = {}
    for track in sorted(tracks, key=lambda t: t.status):
        status_counts[track.status] = status_counts.get(track.status, 0) + 1

    domain_counts: dict[str, int] = {}
    for nb in notebooks:
        domain_counts[nb.domain] = domain_counts.get(nb.domain, 0) + 1
    domain_counts = dict(sorted(domain_counts.items()))

    def gap(items: list[str]) -> list[str]:
        return [f"  - `{item}`" for item in items] if items else ["  - none"]

    no_repo_notebook = sorted(f"{t.id} ({t.status})" for t in tracks if not t.notebooks)
    no_upstream = sorted(nb.path for nb in notebooks if nb.upstream_url is None)
    no_smoke = sorted(nb.path for nb in notebooks if nb.path not in ci_text)
    no_tests = sorted(nb.path for nb in notebooks if not nb.has_tests)

    lines = [
        BANNER,
        "",
        "# Curriculum coverage",
        "",
        "Rollups and gaps derived from the notebooks and `notes/curriculum.toml`.",
        "Regenerate with `just sync`; CI fails when this file is stale.",
        "",
        "## Notebooks by rung",
        "",
        *_count_table(("Rung", "Notebooks"), rung_counts),
        "",
        "## Tracks by status",
        "",
        *_count_table(("Status", "Tracks"), status_counts),
        "",
        "## Notebooks by domain",
        "",
        *_count_table(("Domain", "Notebooks"), domain_counts),
        "",
        "## Gaps",
        "",
        "- Tracks with no notebook in this repo (sibling-repo or study-only rows):",
        *gap(no_repo_notebook),
        "- Notebooks without an upstream link:",
        *gap(no_upstream),
        "- Notebooks without a rung in the registry:",
        *gap(rungless),
        "- Notebooks missing from the CI smoke list:",
        *gap(no_smoke),
        "- Notebooks without `test_*` cells (aspirational, not gated):",
        *gap(no_tests),
        "",
    ]
    return "\n".join(lines)


def render(write: bool = True) -> dict[Path, str]:
    """Render every generated artifact; write them unless dry-running."""
    artifacts = {
        TAXONOMY: render_taxonomy(),
        CATALOG: render_catalog(),
        COVERAGE: render_coverage(),
    }
    if write:
        for path, content in artifacts.items():
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    return artifacts


_SCHEMA = """
CREATE TABLE notebook (
  path        TEXT PRIMARY KEY,
  domain      TEXT, library TEXT, seq INTEGER,
  title       TEXT, summary TEXT,
  track       TEXT, rung TEXT,
  status      TEXT, mastery TEXT,
  upstream_url TEXT,
  packages    TEXT,  -- JSON array, PEP 503-normalized
  tracks      TEXT,  -- JSON array: every claiming track id (M:N)
  headings    TEXT,  -- JSON array
  has_tests   INTEGER, requires_python TEXT
);
CREATE TABLE track (
  id          TEXT PRIMARY KEY,
  domain      TEXT, topic TEXT, mastery TEXT, status TEXT,
  notebooks   TEXT,  -- JSON array of paths (M:N)
  arch_links  TEXT, arch_missing TEXT, sibling TEXT  -- JSON arrays
);
CREATE TABLE project (
  name        TEXT PRIMARY KEY,
  upstream    TEXT, rust_in_python TEXT,
  tracks      TEXT  -- JSON array of track ids (M:N)
);
CREATE TABLE source (
  project   TEXT,    -- FK -> project.name
  component TEXT, title TEXT,
  url       TEXT,    -- version-pinned github blob URL (portable, clone-free)
  tag       TEXT, baseline TEXT
);
CREATE TABLE concept (
  id        TEXT PRIMARY KEY,  -- readable slug (zero-copy, predicate-pushdown)
  gloss     TEXT,              -- one-line definition, our own prose
  projects  TEXT,              -- JSON array of project names the concept appears in
  source    TEXT               -- optional canonical pinned URL
);
-- Conformed-dimension joins: a concept reaches notebooks AND (via project) sources;
-- see-also and lineage are the cross-reference edges. All keyed for instant lookup.
CREATE TABLE notebook_concept ( path TEXT, concept TEXT, PRIMARY KEY(path, concept) );
CREATE TABLE notebook_see_also ( path TEXT, target TEXT, PRIMARY KEY(path, target) );
CREATE TABLE project_lineage (
  project TEXT, derives_from TEXT, PRIMARY KEY(project, derives_from)
);
CREATE INDEX track_status ON track(status);
CREATE INDEX track_domain ON track(domain);
CREATE INDEX project_variation ON project(rust_in_python);
CREATE INDEX notebook_rung ON notebook(rung);
CREATE INDEX source_project ON source(project);
CREATE INDEX notebook_concept_concept ON notebook_concept(concept);
CREATE INDEX project_lineage_parent ON project_lineage(derives_from);
CREATE VIRTUAL TABLE notebook_fts USING fts5(
  path UNINDEXED, body, tokenize='porter unicode61', prefix='2 3'
);
-- Source titles searched on their own grain: most registered projects have no
-- notebook, so their source URLs can only surface from a project-keyed index.
CREATE VIRTUAL TABLE source_fts USING fts5(
  url UNINDEXED, project UNINDEXED, component UNINDEXED, body,
  tokenize='porter unicode61', prefix='2 3'
);
"""


def _notebook_body(path: Path) -> str:
    """Return a notebook's authored text for FTS: docstring + every md/string cell.

    Runtime outputs are never in the ``.py`` file, so they are never indexed.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    return "\n".join(_string_literals(tree))


def build_db(db_path: str = ":memory:") -> sqlite3.Connection:
    """Build the disposable SQLite/FTS5 index from sources.

    Always rebuilt from the notebooks + manifest — the index is never the
    store, so there is no migration story. On disk it must only ever land at
    the gitignored ``.marimo-index.db``.
    """
    notebooks, tracks = index()
    claimed = claims(tracks)
    projects = load_projects()
    conn = sqlite3.connect(db_path)
    conn.executescript(_SCHEMA)
    for nb in notebooks:
        owners = claimed.get(nb.path, [])
        primary = _primary_track(nb, owners)
        conn.execute(
            "INSERT INTO notebook VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (
                nb.path,
                nb.domain,
                nb.library,
                nb.seq,
                nb.title,
                nb.summary,
                nb.track,
                nb.rung,
                primary.status if primary else None,
                primary.mastery if primary else None,
                nb.upstream_url,
                json.dumps(nb.packages),
                json.dumps([t.id for t in owners]),
                json.dumps(nb.headings),
                int(nb.has_tests),
                nb.requires_python,
            ),
        )
        conn.execute(
            "INSERT INTO notebook_fts VALUES (?,?)",
            (nb.path, _notebook_body(REPO_ROOT / nb.path)),
        )
    for t in tracks:
        conn.execute(
            "INSERT INTO track VALUES (?,?,?,?,?,?,?,?,?)",
            (
                t.id,
                t.domain,
                t.topic,
                t.mastery,
                t.status,
                json.dumps([nb["path"] for nb in t.notebooks]),
                json.dumps(t.architecture),
                json.dumps(t.architecture_missing),
                json.dumps(t.sibling_curricula),
            ),
        )
    for proj in projects:
        conn.execute(
            "INSERT INTO project VALUES (?,?,?,?)",
            (proj.name, proj.upstream, proj.rust_in_python, json.dumps(proj.tracks)),
        )
        conn.executemany(
            "INSERT INTO project_lineage VALUES (?,?)",
            [(proj.name, parent) for parent in proj.derives_from],
        )
    for concept in load_concepts():
        conn.execute(
            "INSERT INTO concept VALUES (?,?,?,?)",
            (concept.id, concept.gloss, json.dumps(concept.projects), concept.source),
        )
    for nb in notebooks:
        conn.executemany(
            "INSERT INTO notebook_concept VALUES (?,?)", [(nb.path, c) for c in nb.concepts]
        )
        conn.executemany(
            "INSERT INTO notebook_see_also VALUES (?,?)", [(nb.path, t) for t in nb.see_also]
        )
    for src in load_sources():
        conn.execute(
            "INSERT INTO source VALUES (?,?,?,?,?,?)",
            (
                src["project"],
                src["component"],
                src["title"],
                src["url"],
                src["tag"],
                src["baseline"],
            ),
        )
        conn.execute(
            "INSERT INTO source_fts VALUES (?,?,?,?)",
            (
                src["url"],
                src["project"],
                src["component"],
                f"{src['project']} {src['component']} {src['title']}",
            ),
        )
    conn.commit()
    return conn


def run_query(sql: str) -> int:
    """Execute one SQL statement against a fresh in-memory index; print TSV."""
    conn = build_db()
    cursor = conn.execute(sql)
    if cursor.description:
        print("\t".join(col[0] for col in cursor.description))
    for row in cursor:
        print("\t".join("" if v is None else str(v) for v in row))
    return 0


def run_find(term: str) -> int:
    """Ranked full-text search (bm25) over notebook text and the source map."""
    conn = build_db()
    notebook_rows = conn.execute(
        "SELECT path, bm25(notebook_fts) AS score,"
        " snippet(notebook_fts, 1, '[', ']', '...', 12)"
        " FROM notebook_fts WHERE notebook_fts MATCH ?"
        " ORDER BY bm25(notebook_fts)",
        (term,),
    ).fetchall()
    for path, score, snippet in notebook_rows:
        print(f"{score:7.2f}  {path}")
        print(f"         {' '.join(snippet.split())}")
    source_rows = conn.execute(
        "SELECT project, component, url, bm25(source_fts) AS score"
        " FROM source_fts WHERE source_fts MATCH ?"
        " ORDER BY bm25(source_fts) LIMIT 10",
        (term,),
    ).fetchall()
    for project, component, url, score in source_rows:
        print(f"{score:7.2f}  {project} · {component}")
        print(f"         {url}")
    if not notebook_rows and not source_rows:
        print(f"no FTS matches for {term!r} (rg may still find literal text)")
    return 0


def write_sqlite(output: str) -> int:
    """Write the index to a gitignored on-disk cache for repeated queries."""
    target = Path(output)
    if target.exists():
        target.unlink()
    build_db(str(target)).close()
    print(f"wrote {output} (gitignored, disposable — rebuild any time)")
    return 0


@dataclass
class CheckResult:
    """The drift gate's findings, separated from output for unit testing."""

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    notebooks: int = 0
    tracks: int = 0
    projects: int = 0


def slug_format_errors(tracks: list[Track]) -> list[str]:
    """Every track id must be a lowercase ``domain/slug`` — no mystery-meat codes."""
    return [
        f"track id {t.id!r} is not a domain/slug (lowercase, hyphenated)"
        for t in tracks
        if not _SLUG_RE.match(t.id)
    ]


def library_project_errors(notebooks: list[Notebook], projects: list[Project]) -> list[str]:
    """Every notebook library must resolve to a [[project]] entry."""
    names = {p.name for p in projects}
    return [
        f"{nb.path}: library {nb.library!r} has no [[project]] entry"
        for nb in notebooks
        if nb.library not in names
    ]


def project_track_errors(tracks: list[Track], projects: list[Project]) -> list[str]:
    """Every project's `tracks` must reference an existing track id."""
    ids = {t.id for t in tracks}
    return [
        f"project {p.name!r}: references unknown track {tid!r}"
        for p in projects
        for tid in p.tracks
        if tid not in ids
    ]


def cross_reference_errors(
    notebooks: list[Notebook], concepts: list[Concept], projects: list[Project]
) -> list[str]:
    """Validate the opt-in cross-reference layer: tags, see-also, and lineage.

    Concept tags must name a registered concept; see-also must point at a real
    notebook; project lineage must name a real project. Untagged notebooks are
    fine — the layer is opt-in, so this never forces a notebook to carry it.
    """
    concept_ids = {c.id for c in concepts}
    paths = {nb.path for nb in notebooks}
    names = {p.name for p in projects}
    errors = [
        f"{nb.path}: unknown concept {tag!r} (add it to [[concept]] in curriculum.toml)"
        for nb in notebooks
        for tag in nb.concepts
        if tag not in concept_ids
    ]
    errors += [
        f"{nb.path}: see-also points at missing notebook {target!r}"
        for nb in notebooks
        for target in nb.see_also
        if target not in paths
    ]
    errors += [
        f"project {p.name!r}: derives_from unknown project {parent!r}"
        for p in projects
        for parent in p.derives_from
        if parent not in names
    ]
    return errors


def check_drift() -> CheckResult:
    """Compute drift findings: errors (gate-failing) and warnings (advisory)."""
    notebooks, tracks = index()
    projects = load_projects()
    result = CheckResult(notebooks=len(notebooks), tracks=len(tracks), projects=len(projects))
    errors, warnings = result.errors, result.warnings

    claimed = claims(tracks)
    errors.extend(
        f"{track.id}: claims missing file {entry['path']}"
        for track in tracks
        for entry in track.notebooks
        if not (REPO_ROOT / entry["path"]).exists()
    )

    # Rename-hazard parity: a `git mv` or an unclaimed new notebook fails here.
    errors.extend(
        f"unclaimed notebook (no [[track]] lists it): {nb.path}"
        for nb in notebooks
        if nb.path not in claimed
    )

    # Project registry: every notebook library resolves to a project, and every
    # project points at real tracks. Track ids stay readable slugs.
    errors.extend(slug_format_errors(tracks))
    errors.extend(library_project_errors(notebooks, projects))
    errors.extend(project_track_errors(tracks, projects))
    errors.extend(source_map_errors(projects))
    errors.extend(cross_reference_errors(notebooks, load_concepts(), projects))

    ci_text = CI_WORKFLOW.read_text(encoding="utf-8")
    warnings.extend(
        f"{nb.path}: not in the ci.yml smoke step (hand-maintained — add it or note why not)"
        for nb in notebooks
        if nb.path not in ci_text
    )

    project_names = {p.name for p in projects}
    warnings.extend(
        f"concept {c.id!r}: lists unknown project {name!r}"
        for c in load_concepts()
        for name in c.projects
        if name not in project_names
    )

    for path, content in render(write=False).items():
        rel = path.relative_to(REPO_ROOT)
        if not path.exists():
            errors.append(f"{rel}: missing — run `uv run scripts/curriculum.py render`")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"{rel}: stale — run `uv run scripts/curriculum.py render`")

    return result


def report_drift() -> int:
    """Print drift findings and return the process exit code (0 ok, 1 drift)."""
    result = check_drift()
    for warning in result.warnings:
        print(f"WARN  {warning}")
    for error in result.errors:
        print(f"DRIFT {error}")
    if result.errors:
        print(
            f"Curriculum drift: {len(result.errors)} error(s), {len(result.warnings)} warning(s)."
        )
        return 1
    print(
        f"Curriculum drift: OK ({result.notebooks} notebooks, {result.tracks} tracks, "
        f"{result.projects} projects, {len(result.warnings)} warning(s))"
    )
    return 0


def main() -> int:
    """CLI: render (write generated files) or check (the CI drift gate)."""
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser(
        "render",
        help="regenerate notes/{taxonomy.md,catalog.jsonl,coverage.md} from the sources",
    )
    sub.add_parser("check", help="exit nonzero on drift between sources and renders")
    sub.add_parser(
        "sources", help="rebuild notes/sources.jsonl from the architecture corpus (local)"
    )
    query = sub.add_parser("query", help="SQL over the in-memory index (TSV output)")
    query.add_argument("sql")
    find = sub.add_parser("find", help="ranked FTS5 search (bm25 + snippets)")
    find.add_argument("term")
    sqlite_cmd = sub.add_parser("sqlite", help="write the index to a gitignored file")
    sqlite_cmd.add_argument("--output", default=".marimo-index.db")
    args = parser.parse_args()
    if args.command == "render":
        render()
        return 0
    if args.command == "sources":
        return run_sources()
    if args.command == "query":
        return run_query(args.sql)
    if args.command == "find":
        return run_find(args.term)
    if args.command == "sqlite":
        return write_sqlite(args.output)
    return report_drift()


if __name__ == "__main__":
    sys.exit(main())
