#!/usr/bin/env python3
"""Curriculum catalog: parse notebooks + the track manifest, derive the index.

Notebooks own their mechanical metadata (docstring, ``(Track, Rung)`` tag,
``app_title``, PEP 723 deps, headings, source-reading links). The authored
overlay — topic prose, mastery, status, architecture pointers, and the M:N
track↔notebook links — lives in ``notes/curriculum.toml``. This script merges
the two grains and renders ``notes/taxonomy.md`` (generated, never
hand-edited); ``check`` exits nonzero when a committed render is stale or the
sources disagree, which is what CI runs.

Stdlib-only on purpose (``tomllib`` + ``re`` + ``ast``): runs under
``uv run`` with zero added dependencies, same as ``check_licenses.py``,
whose PEP 723 helpers it reuses.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path

from check_licenses import _BLOCK_RE, dependency_name, pep723_dependencies

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "notes" / "curriculum.toml"
TAXONOMY = REPO_ROOT / "notes" / "taxonomy.md"
HEAD = REPO_ROOT / "notes" / "taxonomy.head.md"
FOOT = REPO_ROOT / "notes" / "taxonomy.foot.md"
CATALOG = REPO_ROOT / "notes" / "catalog.jsonl"
COVERAGE = REPO_ROOT / "notes" / "coverage.md"
CI_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "ci.yml"

BANNER = (
    "<!-- generated by scripts/curriculum.py render — edit notes/curriculum.toml"
    " and the notebooks, not this file -->"
)

#: Docstring tag, anchored to the end of the summary line: ``(B1, L2)``.
_TAG_RE = re.compile(r"\((?P<track>[A-Za-z0-9]+), (?P<rung>L[1-4])\)\.?\s*$")
_APP_TITLE_RE = re.compile(r'app_title="(?P<title>[^"]+)"')
_UPSTREAM_RE = re.compile(r"Upstream: <(?P<url>https://[^>]+)>")
_CLONE_RE = re.compile(r"Local clone [^:]*: `(?P<path>[^`]+)`")
_HEADING_RE = re.compile(r"^\s*#{1,6} +(?P<text>\S.*)$", re.MULTILINE)


@dataclass
class Notebook:
    """Grain A — one record per notebook file, all fields parsed from it."""

    path: str
    domain: str
    library: str
    seq: int
    title: str
    summary: str
    track: str | None
    rung: str | None
    packages: list[str]
    requires_python: str | None
    headings: list[str]
    has_tests: bool
    upstream_url: str | None
    clone_path: str | None


@dataclass
class Track:
    """Grain B — one record per taxonomy row, authored in curriculum.toml."""

    id: str
    domain: str
    topic: str
    mastery: str
    status: str
    notebooks: list[dict[str, str]]
    note: str | None = None
    sibling_curricula: list[str] = field(default_factory=list)
    architecture: list[str] = field(default_factory=list)
    architecture_missing: list[str] = field(default_factory=list)
    packages: str = ""
    license_status: str = ""


def _string_literals(tree: ast.Module) -> list[str]:
    """Collect every string constant in the module — mo.md bodies, docstrings."""
    return [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
    ]


def _requires_python(source: str) -> str | None:
    """Return the PEP 723 block's ``requires-python`` field, if present."""
    match = _BLOCK_RE.search(source)
    if match is None:
        return None
    import tomllib

    toml_text = "\n".join(
        line.removeprefix("# ").removeprefix("#") for line in match.group(1).splitlines()
    )
    value = tomllib.loads(toml_text).get("requires-python")
    return str(value) if value is not None else None


def parse_notebook(path: Path) -> Notebook:
    """Parse one notebook file into its Grain-A record."""
    rel = path.relative_to(REPO_ROOT).as_posix()
    _, domain, library, filename = rel.split("/", 3)
    seq = int(filename.split("_", 1)[0])
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    docstring = ast.get_docstring(tree) or ""
    summary_line = docstring.splitlines()[0] if docstring else ""

    tag = _TAG_RE.search(summary_line)
    track = tag.group("track") if tag else None
    rung = tag.group("rung") if tag else None
    summary = _TAG_RE.sub("", summary_line).rstrip()
    if summary and not summary.endswith("."):
        summary += "."

    title_match = _APP_TITLE_RE.search(source)
    title = title_match.group("title") if title_match else summary

    literals = _string_literals(tree)
    headings = [
        m.group("text").strip()
        for text in literals
        if "\n" in text
        for m in _HEADING_RE.finditer(text)
    ]
    upstream = next((m.group("url") for s in literals for m in [_UPSTREAM_RE.search(s)] if m), None)
    clone = next((m.group("path") for s in literals for m in [_CLONE_RE.search(s)] if m), None)

    return Notebook(
        path=rel,
        domain=domain,
        library=library,
        seq=seq,
        title=title,
        summary=summary,
        track=track,
        rung=rung,
        packages=sorted({dependency_name(r) for r in pep723_dependencies(path)}),
        requires_python=_requires_python(source),
        headings=headings,
        has_tests=bool(re.search(r"^def test_", source, re.MULTILINE)),
        upstream_url=upstream,
        clone_path=clone,
    )


def load_tracks() -> list[Track]:
    """Load the authored track overlay from notes/curriculum.toml."""
    import tomllib

    with MANIFEST.open("rb") as f:
        data = tomllib.load(f)
    return [Track(**raw) for raw in data["track"]]


def load_ladder() -> dict[str, str]:
    """Return the short rung labels (L1..L4) used to caption rollups."""
    import tomllib

    with MANIFEST.open("rb") as f:
        return dict(tomllib.load(f)["ladder"])


def notebook_paths() -> list[Path]:
    """Every notebook on disk, sorted (the template is not a notebook)."""
    return sorted(REPO_ROOT.glob("notebooks/**/*.py"))


def index() -> tuple[list[Notebook], list[Track]]:
    """Return the merged model: parsed notebooks + the authored track overlay."""
    return [parse_notebook(p) for p in notebook_paths()], load_tracks()


def _notebook_cell(track: Track) -> str:
    """Render one row's Notebook column: links · ✎ siblings (note)."""
    items = [f"[{nb.get('label', nb['path'])}](../{nb['path']})" for nb in track.notebooks]
    items.extend(track.sibling_curricula)
    cell = " · ".join(items) if items else "—"
    if track.note:
        cell += f" ({track.note})"
    return cell


def _architecture_cell(track: Track) -> str:
    """Render one row's Architecture column: `architecture/{...}` (missing: ...)."""
    parts: list[str] = []
    if track.architecture:
        parts.append("`architecture/{" + ",".join(track.architecture) + "}`")
    if track.architecture_missing:
        parts.append("(missing: " + ", ".join(track.architecture_missing) + ")")
    return " ".join(parts) if parts else "—"


def render_taxonomy() -> str:
    """Render the full generated notes/taxonomy.md content."""
    tracks = load_tracks()
    rows = [
        "| Domain | Track | Topic | Notebook | Architecture study | Packages "
        "| License status | Mastery | Status |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    rows.extend(
        f"| {t.domain} | {t.id} | {t.topic} | {_notebook_cell(t)} "
        f"| {_architecture_cell(t)} | {t.packages} | {t.license_status} "
        f"| {t.mastery} | {t.status} |"
        for t in tracks
    )
    head = HEAD.read_text(encoding="utf-8").strip("\n")
    foot = FOOT.read_text(encoding="utf-8").strip("\n")
    return "\n".join([BANNER, "", head, "", *rows, "", foot, ""])


def claims(tracks: list[Track]) -> dict[str, list[Track]]:
    """Map each claimed notebook path to the tracks that list it."""
    claimed: dict[str, list[Track]] = {}
    for track in tracks:
        for nb in track.notebooks:
            claimed.setdefault(nb["path"], []).append(track)
    return claimed


def _primary_track(notebook: Notebook, owners: list[Track]) -> Track | None:
    """Pick the notebook's primary track: its docstring tag, else first claimer."""
    for track in owners:
        if track.id == notebook.track:
            return track
    return owners[0] if owners else None


def render_catalog() -> str:
    """Render notes/catalog.jsonl — one merged record per notebook, for jq/DuckDB."""
    notebooks, tracks = index()
    claimed = claims(tracks)
    lines = []
    for nb in notebooks:
        owners = claimed.get(nb.path, [])
        primary = _primary_track(nb, owners)
        record = {
            "path": nb.path,
            "domain": nb.domain,
            "library": nb.library,
            "seq": nb.seq,
            "title": nb.title,
            "summary": nb.summary,
            "track": nb.track,
            "rung": nb.rung,
            "tracks": [t.id for t in owners],
            "status": primary.status if primary else None,
            "mastery": primary.mastery if primary else None,
            "packages": nb.packages,
            "requires_python": nb.requires_python,
            "headings": nb.headings,
            "has_tests": nb.has_tests,
            "upstream_url": nb.upstream_url,
            "clone_path": nb.clone_path,
        }
        lines.append(json.dumps(record, ensure_ascii=False))
    return "\n".join(lines) + "\n"


def _count_table(header: tuple[str, str], counts: dict[str, int]) -> list[str]:
    """Render a two-column markdown count table."""
    rows = [f"| {header[0]} | {header[1]} |", "|---|---|"]
    rows.extend(f"| {key} | {count} |" for key, count in counts.items())
    return rows


def render_coverage() -> str:
    """Render notes/coverage.md — rollups and gap lists over the merged model."""
    notebooks, tracks = index()
    ladder = load_ladder()
    ci_text = CI_WORKFLOW.read_text(encoding="utf-8")

    rung_counts = {
        f"{rung} — {label}": sum(1 for nb in notebooks if nb.rung == rung)
        for rung, label in ladder.items()
    }
    untagged = sorted(nb.path for nb in notebooks if nb.rung is None)
    if untagged:
        rung_counts["untagged"] = len(untagged)

    status_counts: dict[str, int] = {}
    for track in sorted(tracks, key=lambda t: t.status):
        status_counts[track.status] = status_counts.get(track.status, 0) + 1

    domain_counts: dict[str, int] = {}
    for nb in notebooks:
        domain_counts[nb.domain] = domain_counts.get(nb.domain, 0) + 1
    domain_counts = dict(sorted(domain_counts.items()))

    def gap(items: list[str]) -> list[str]:
        return [f"  - `{item}`" for item in items] if items else ["  - none"]

    no_repo_notebook = sorted(f"{t.id} ({t.status})" for t in tracks if not t.notebooks)
    no_clone = sorted(nb.path for nb in notebooks if nb.clone_path is None)
    no_upstream = sorted(nb.path for nb in notebooks if nb.upstream_url is None)
    no_smoke = sorted(nb.path for nb in notebooks if nb.path not in ci_text)
    no_tests = sorted(nb.path for nb in notebooks if not nb.has_tests)

    lines = [
        BANNER,
        "",
        "# Curriculum coverage",
        "",
        "Rollups and gaps derived from the notebooks and `notes/curriculum.toml`.",
        "Regenerate with `just sync`; CI fails when this file is stale.",
        "",
        "## Notebooks by rung",
        "",
        *_count_table(("Rung", "Notebooks"), rung_counts),
        "",
        "## Tracks by status",
        "",
        *_count_table(("Status", "Tracks"), status_counts),
        "",
        "## Notebooks by domain",
        "",
        *_count_table(("Domain", "Notebooks"), domain_counts),
        "",
        "## Gaps",
        "",
        "- Tracks with no notebook in this repo (sibling-repo or study-only rows):",
        *gap(no_repo_notebook),
        "- Notebooks without a `Local clone` pointer (no local clone exists):",
        *gap(no_clone),
        "- Notebooks without an upstream link:",
        *gap(no_upstream),
        "- Notebooks without a `(Track, Rung)` docstring tag:",
        *gap(untagged),
        "- Notebooks missing from the CI smoke list:",
        *gap(no_smoke),
        "- Notebooks without `test_*` cells (aspirational, not gated):",
        *gap(no_tests),
        "",
    ]
    return "\n".join(lines)


def render(write: bool = True) -> dict[Path, str]:
    """Render every generated artifact; write them unless dry-running."""
    artifacts = {
        TAXONOMY: render_taxonomy(),
        CATALOG: render_catalog(),
        COVERAGE: render_coverage(),
    }
    if write:
        for path, content in artifacts.items():
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    return artifacts


_SCHEMA = """
CREATE TABLE notebook (
  path        TEXT PRIMARY KEY,
  domain      TEXT, library TEXT, seq INTEGER,
  title       TEXT, summary TEXT,
  track       TEXT, rung TEXT,
  status      TEXT, mastery TEXT,
  upstream_url TEXT, clone_path TEXT,
  packages    TEXT,  -- JSON array, PEP 503-normalized
  tracks      TEXT,  -- JSON array: every claiming track id (M:N)
  headings    TEXT,  -- JSON array
  has_tests   INTEGER, requires_python TEXT
);
CREATE TABLE track (
  id          TEXT PRIMARY KEY,
  domain      TEXT, topic TEXT, mastery TEXT, status TEXT,
  notebooks   TEXT,  -- JSON array of paths (M:N)
  arch_links  TEXT, arch_missing TEXT, sibling TEXT  -- JSON arrays
);
CREATE INDEX track_status ON track(status);
CREATE INDEX track_domain ON track(domain);
CREATE INDEX notebook_rung ON notebook(rung);
CREATE VIRTUAL TABLE notebook_fts USING fts5(
  path UNINDEXED, body, tokenize='porter unicode61', prefix='2 3'
);
"""


def _notebook_body(path: Path) -> str:
    """Return a notebook's authored text for FTS: docstring + every md/string cell.

    Runtime outputs are never in the ``.py`` file, so they are never indexed.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    return "\n".join(_string_literals(tree))


def build_db(db_path: str = ":memory:") -> sqlite3.Connection:
    """Build the disposable SQLite/FTS5 index from sources.

    Always rebuilt from the notebooks + manifest — the index is never the
    store, so there is no migration story. On disk it must only ever land at
    the gitignored ``.marimo-index.db``.
    """
    notebooks, tracks = index()
    claimed = claims(tracks)
    conn = sqlite3.connect(db_path)
    conn.executescript(_SCHEMA)
    for nb in notebooks:
        owners = claimed.get(nb.path, [])
        primary = _primary_track(nb, owners)
        conn.execute(
            "INSERT INTO notebook VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (
                nb.path,
                nb.domain,
                nb.library,
                nb.seq,
                nb.title,
                nb.summary,
                nb.track,
                nb.rung,
                primary.status if primary else None,
                primary.mastery if primary else None,
                nb.upstream_url,
                nb.clone_path,
                json.dumps(nb.packages),
                json.dumps([t.id for t in owners]),
                json.dumps(nb.headings),
                int(nb.has_tests),
                nb.requires_python,
            ),
        )
        conn.execute(
            "INSERT INTO notebook_fts VALUES (?,?)",
            (nb.path, _notebook_body(REPO_ROOT / nb.path)),
        )
    for t in tracks:
        conn.execute(
            "INSERT INTO track VALUES (?,?,?,?,?,?,?,?,?)",
            (
                t.id,
                t.domain,
                t.topic,
                t.mastery,
                t.status,
                json.dumps([nb["path"] for nb in t.notebooks]),
                json.dumps(t.architecture),
                json.dumps(t.architecture_missing),
                json.dumps(t.sibling_curricula),
            ),
        )
    conn.commit()
    return conn


def run_query(sql: str) -> int:
    """Execute one SQL statement against a fresh in-memory index; print TSV."""
    conn = build_db()
    cursor = conn.execute(sql)
    if cursor.description:
        print("\t".join(col[0] for col in cursor.description))
    for row in cursor:
        print("\t".join("" if v is None else str(v) for v in row))
    return 0


def run_find(term: str) -> int:
    """Ranked full-text search (bm25) with snippets over notebook text."""
    conn = build_db()
    rows = conn.execute(
        "SELECT path, bm25(notebook_fts) AS score,"
        " snippet(notebook_fts, 1, '[', ']', '...', 12)"
        " FROM notebook_fts WHERE notebook_fts MATCH ?"
        " ORDER BY bm25(notebook_fts)",
        (term,),
    ).fetchall()
    for path, score, snippet in rows:
        print(f"{score:7.2f}  {path}")
        print(f"         {' '.join(snippet.split())}")
    if not rows:
        print(f"no FTS matches for {term!r} (rg may still find literal text)")
    return 0


def write_sqlite(output: str) -> int:
    """Write the index to a gitignored on-disk cache for repeated queries."""
    target = Path(output)
    if target.exists():
        target.unlink()
    build_db(str(target)).close()
    print(f"wrote {output} (gitignored, disposable — rebuild any time)")
    return 0


def check_drift() -> int:
    """Drift gate: nonzero when sources disagree or a render is stale."""
    notebooks, tracks = index()
    errors: list[str] = []
    warnings: list[str] = []

    claimed = claims(tracks)
    errors.extend(
        f"{track.id}: claims missing file {entry['path']}"
        for track in tracks
        for entry in track.notebooks
        if not (REPO_ROOT / entry["path"]).exists()
    )

    # Rename-hazard parity: a `git mv` or an unclaimed new notebook fails here.
    for nb in notebooks:
        owners = claimed.get(nb.path, [])
        if not owners:
            errors.append(f"unclaimed notebook (no [[track]] lists it): {nb.path}")
        elif nb.track is not None and nb.track not in [t.id for t in owners]:
            warnings.append(
                f"{nb.path}: docstring tag ({nb.track}) is not a claiming track "
                f"({', '.join(t.id for t in owners)})"
            )
        if nb.track is None:
            warnings.append(f"{nb.path}: no (Track, Rung) docstring tag")

    ci_text = CI_WORKFLOW.read_text(encoding="utf-8")
    warnings.extend(
        f"{nb.path}: not in the ci.yml smoke step (hand-maintained — add it or note why not)"
        for nb in notebooks
        if nb.path not in ci_text
    )

    for path, content in render(write=False).items():
        rel = path.relative_to(REPO_ROOT)
        if not path.exists():
            errors.append(f"{rel}: missing — run `uv run scripts/curriculum.py render`")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"{rel}: stale — run `uv run scripts/curriculum.py render`")

    for warning in warnings:
        print(f"WARN  {warning}")
    for error in errors:
        print(f"DRIFT {error}")
    if errors:
        print(f"Curriculum drift: {len(errors)} error(s), {len(warnings)} warning(s).")
        return 1
    print(
        f"Curriculum drift: OK ({len(notebooks)} notebooks, {len(tracks)} tracks, "
        f"{len(warnings)} warning(s))"
    )
    return 0


def main() -> int:
    """CLI: render (write generated files) or check (the CI drift gate)."""
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser(
        "render",
        help="regenerate notes/{taxonomy.md,catalog.jsonl,coverage.md} from the sources",
    )
    sub.add_parser("check", help="exit nonzero on drift between sources and renders")
    query = sub.add_parser("query", help="SQL over the in-memory index (TSV output)")
    query.add_argument("sql")
    find = sub.add_parser("find", help="ranked FTS5 search (bm25 + snippets)")
    find.add_argument("term")
    sqlite_cmd = sub.add_parser("sqlite", help="write the index to a gitignored file")
    sqlite_cmd.add_argument("--output", default=".marimo-index.db")
    args = parser.parse_args()
    if args.command == "render":
        render()
        return 0
    if args.command == "query":
        return run_query(args.sql)
    if args.command == "find":
        return run_find(args.term)
    if args.command == "sqlite":
        return write_sqlite(args.output)
    return check_drift()


if __name__ == "__main__":
    sys.exit(main())
